language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=maps
  matrix:
    - DB=sqlite

branches:
  only:
    - master

before_install:
#  - composer install
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable $APP_NAME

script:
  # Test lint
  - cd apps/$APP_NAME
  # Test lint
  - find . -name \*.php -not -path './vendor/*' -exec php -l "{}" \;

  # Run phpunit tests
  - phpunit --configuration phpunit.xml

  # Create coverage report
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

matrix:
  include:
    - php: 7.0
      env: DB=mysql
    - php: 7.0
      env: DB=pgsql
    - php: 5.4
      env: "DB=mysql CORE_BRANCH=stable8.2"
    - php: 5.4
      env: "DB=mysql CORE_BRANCH=stable9"
    - php: 5.4
      env: "DB=mysql CORE_BRANCH=stable9.1"
  fast_finish: true
